# Use the specified PyTorch base image with CUDA support
FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-runtime AS xmem2-base-inference

# Set the working directory in the container
WORKDIR /app

# Copy the application files into the container
COPY . /app

RUN python -m pip install --no-cache-dir opencv-python-headless scikit-learn Pillow==9.2.0

# Install Python dependencies from requirements.txt
RUN python -m pip install --no-cache-dir -r requirements.txt

# # Default executable
# ENTRYPOINT ["python3", "process_video.py"]
